language: perl
services:
  - "docker"
perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6"
  - "echo 'deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.4 main' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org-server"
install:
  - "cpanm -n --installdeps ."
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
script:
  - "prove -l"
notifications:
email:
  - "andrey@rydlab.ru"
  - "mw26@rydlab.ru"
