language: perl
services:
  - "docker"
perl:
  - "5.18"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927"
  - "echo 'deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org-server"
  - "sudo apt-get install -y mongodb-org-server"
install:
  - "cpanm -n --installdeps ."
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
script:
  - "prove -l"
notifications:
  email: andrey@rydlab.ru
