language: perl
perl:
  - "5.18"
env:
  - "MOJO_MODE=test"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
install:
  - "cpanm -n --installdeps ."
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
script:
  - "./script/jagc test -v"
notifications:
  email: avkhozov@gmail.com
